### ISSUE TITLE
Create user model

### ISSUE THREAD

**Issue by vol6tmetr** [Matveibos/Recruitment_Agency#26]
Subtasks:
- [x] [Generate user model with all needed fields](https://github.com/Matveibos/Recruitment_Agency/issues/28)
- [x] [Add devise gem](https://github.com/Matveibos/Recruitment_Agency/issues/27)
- [x] [Add user authentication](https://github.com/Matveibos/Recruitment_Agency/issues/7)
- [x] [Add pundit gem](https://github.com/Matveibos/Recruitment_Agency/issues/29)
- [ ] [Add user authorization](https://github.com/Matveibos/Recruitment_Agency/issues/30) (policies for user, manager and admin roles)
- [ ] [Add test users to the seeds](https://github.com/Matveibos/Recruitment_Agency/issues/31)
